# Generated by Django 3.2.9 on 2021-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=None, max_length=100)),
                ('category', models.CharField(default=None, max_length=50)),
                ('name', models.CharField(default=None, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('timestamp', models.DateField()),
                ('has_errors', models.BooleanField(default=False)),
            ],
        ),
    ]
